# -*- coding: utf-8 -*-
"""my yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J00Ok6nvNZ2Gglmx6duoBGeYJ4kHl69a
"""

!pip install opencv-python ultralytics pandas matplotlib

import cv2
from ultralytics import YOLO
import numpy as np
from google.colab.patches import cv2_imshow  # Colab-specific display
from datetime import datetime
import pandas as pd

# Load YOLOv8 model
model = YOLO("yolov8n.pt")  # Auto-downloads if not present

image_path = '/content/Screenshot (6133).png'
frame = cv2.imread(image_path)  # Load your image

# Check if image loaded correctly
if frame is None:
    raise FileNotFoundError(f"Image not found at {image_path}")

# People counting function
def count_people(frame):
    results = model(frame, classes=[0])  # Class 0 = person
    return len(results[0].boxes)

# Initialize logging
log = []

# === REPLACE THE LOOP WITH ===
count = count_people(frame)
log = [{"timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "people_count": count}]

# Annotate and display
cv2.putText(frame, f"People: {count}", (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
cv2_imshow(frame)

results = model(frame, classes=[0])
count = len(results[0].boxes)
annotated_frame = results[0].plot()  # Adds boxes to the image
cv2_imshow(annotated_frame)

# Save logs to DataFrame
df = pd.DataFrame(log)
print("\nLogs:")
print(df)

